## Stage 1 : build with maven builder image with native capabilities
FROM gradle:jdk21-ubi-minimal AS build
USER root
RUN microdnf install findutils -y
COPY --chown=gradle:gradle gradlew /code/gradlew
COPY --chown=gradle:gradle gradle /code/gradle
COPY --chown=gradle:gradle build.gradle /code/
COPY --chown=gradle:gradle settings.gradle /code/
COPY --chown=gradle:gradle gradle.properties /code/
USER gradle
WORKDIR /code
COPY src /code/src
RUN ./gradlew dependencies
RUN ./gradlew build

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi9/openjdk-21:1.23 AS final

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 /code/build/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /code/build/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /code/build/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /code/build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]